---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx</title>
    </head>
    <body style="background-color: green;">
        <h1>Hello, Nginx!</h1>
    </body>
    </html>
