---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cat-pics
          mountPath: /usr/share/nginx/html/images
      volumes:
      - name: cat-pics
        persistentVolumeClaim:
          claimName: cat-pics-pvc
